/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT
 */

package cmd

import (
	"log"
	"strconv"
)

//获取命令行輸入內容
type Input struct {
	Y int //年
	M int //月
	D int //日
	H int //時
}

//阳历年月日时數字
func GetInPut(s *string) *Input {
	rs := []rune(*s)
	ys := string(rs[:4])
	ms := string(rs[4:6])
	ds := string(rs[6:8])
	hs := string(rs[8:10])

	y, err := strconv.Atoi(ys)
	if err != nil {
		log.Fatal("年份時間解析:", err)
	}

	m, err := strconv.Atoi(ms)
	if err != nil {
		log.Fatal("月份時間解析:", err)
	}
	d, err := strconv.Atoi(ds)
	if err != nil {
		log.Fatal("日期時間解析:", err)
	}
	h, err := strconv.Atoi(hs)
	if err != nil {
		log.Fatal("時辰解析:", err)
	}

	return &Input{
		Y: y,
		D: d,
		M: m,
		H: h,
	}
}
