/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT
 */

package cmd

import (
	"fmt"
	"os"
)

var (
	Version   = ""
	GoVersion = ""
	Mail      = ""
	BuildTime = ""
)

//输出版本信息
func PrintVersion() {
	fmt.Printf("Version: %s\n", Version)
	fmt.Printf("%s\n", GoVersion)
	fmt.Printf("Mail: %s\n", Mail)
	fmt.Printf("Build Time: %s\n", BuildTime)
	os.Exit(0)
}
