#!/bin/bash

#
# The code is automatically generated by the Goland.
# Copyright © Aquarian-Age. All Rights Reserved.
# Licensed under MIT
#

version="1.0.0"
gov=$(go version)
mail="aaa@bbb"
time=$(date +"%Y-%m-%d %H:%M:%S")
path="github.com/Aquarian-Age/xa/pkg/cmd"

flags="
-X $path.Version=$version
-X '$path.GoVersion=$gov'
-X '$path.BuildTime=$time'
-X $path.Mail=$mail
-s -w"

go build -ldflags "$flags" -o example .