/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT
 */

package main

import (
	"flag"

	"github.com/Aquarian-Age/xa/pkg/cmd"
)

var printVersion bool

func main() {
	flag.BoolVar(&printVersion, "version", false, "print version")
	flag.Parse()
	if printVersion {
		cmd.PrintVersion()
	}
}

/*
Version: 1.0.0
Go Version: 1.16.2 linux/amd64
Git Commit: d903a2678d3b125c5e257ac77e5745fddeaa804a
Build Time: 2021-07-31 15:50:17
*/
