/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT.
 */

package jingwei

import (
	"fmt"
	"github.com/starainrt/astro/sun"
	"log"
	"time"
)

type Sun struct {
	Jing      float64 `json:"jing"`
	Wei       float64 `json:"wei"`
	ShengQi   string  `json:"up"`
	LuoXia    string  `json:"luo_xia"`
	ZhongTian string  `json:"zhong_tian"`
	HuangChi  string  `json:"huang_chi"`
	HuangJing string  `json:"huang_jing"`
	JuLi      string  `json:"ju_li"`
}

//传入经纬度　获取太阳时间
func GetSun(j, w float64) *Sun {
	//layout := "2006-01-02 15:04:05"
	layout := "15:04:05"
	//太阳升起时间
	t1, err := sun.RiseTime(time.Now().Local(), j, w, 0, true)
	if err != nil {
		log.Fatal(err)
	}
	//太阳落下时间
	t2, err := sun.DownTime(time.Now().Local(), j, w, 0, true)
	if err != nil {
		log.Fatal(err)
	}
	//太阳中天时间
	t3 := sun.CulminationTime(time.Now().Local(), j)
	//黄赤交角
	t4 := sun.EclipticObliquity(time.Now().Local(), true)
	//太阳真黄径
	t5 := sun.TrueLo(time.Now().Local())
	//太阳日地距离
	t6 := sun.EarthDistance(time.Now().Local())

	t1s := t1.Format(layout)
	t2s := t2.Format(layout)
	t3s := t3.Format(layout)

	t4s := fmt.Sprintf("%f", t4)
	t5s := fmt.Sprintf("%f", t5)
	t6s := fmt.Sprintf("%f", t6)
	return &Sun{
		j,
		w,
		t1s,
		t2s,
		t3s,
		t4s,
		t5s,
		t6s,
	}
}
