/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT
 */

// Package gz 干支计算
// 六十甲子 五行生克 十二长生 十干禄位 纳因 年月日时干支 咸池 华盖 黄黑　建除 日禽
//月将 贵人 天三门 地四户 地私门 太冲天马 登天门 阴历 朔望
package gz
