/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT.
 */

package gz

import (
	"math"
)

// AliasGan 日干 1+mod(JD正午-1,10) 这里传入的JD是时间精确到日计算
func AliasGan(jd float64) string {
	n := int(math.Ceil(math.Mod(jd-1, 10)))
	gans := []string{"甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"}
	if n > 9 {
		n -= 10
	}
	return gans[n]
}
