/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT.
 */

package gz

import (
	"math"
	"strings"
)

var (
	changShengNames = []string{"长生", "沐浴", "冠带", "临官", "帝旺", "衰", "病", "死", "墓", "绝", "胎", "养"}
	// k:天干 v 0:长生 1:沐浴 2冠带 3临官 4帝旺 5衰 6病 7死 8墓 9绝 10胎 11:养
	changShengMap = map[string][]string{
		"甲": {"亥", "子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌"},
		"丙": {"寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥", "子", "丑"},
		"戊": {"寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥", "子", "丑"},
		"庚": {"巳", "午", "未", "申", "酉", "戌", "亥", "子", "丑", "寅", "卯", "辰"},
		"壬": {"申", "酉", "戌", "亥", "子", "丑", "寅", "卯", "辰", "巳", "午", "未"},
		"乙": {"午", "巳", "辰", "卯", "寅", "丑", "子", "亥", "戌", "酉", "申", "未"},
		"丁": {"酉", "申", "未", "午", "巳", "辰", "卯", "寅", "丑", "子", "亥", "戌"},
		"己": {"酉", "申", "未", "午", "巳", "辰", "卯", "寅", "丑", "子", "亥", "戌"},
		"辛": {"子", "亥", "戌", "酉", "申", "未", "午", "巳", "辰", "卯", "寅", "丑"},
		"癸": {"卯", "寅", "丑", "子", "亥", "戌", "酉", "申", "未", "午", "巳", "辰"},
	}
	shiGanYiXiangMap = map[string]string{
		"甲": `头 胆 树木 第一 首领 领导 功名 科甲 青色 酸味 栋梁 开始 仁慈 东方 毛发 一数 九数 愤怒 帽子`,
		"乙": `肩 肝 花草之木 第二 绿色 酸味 仁慈 妻子 辫子 毛发 胡须，乞丐 磕头作揖 善良 东方 二数 八数 毛巾 围巾`,
		"丙": `额 小肠 太阳 熊熊烈火 炽热 红色 第三 权威 急躁 礼貌 光明 温暖 南方 苦味 眼睛 大眼睛 笑容 大笑 三数 七数`,
		"丁": `心 齿舌 眼睛 小眼睛 玉女 紫红色 苦味 南方 补丁 图钉 钢钉 钉书器 花朵 礼貌 四数 六数 微笑 星星 灯光 烛光 生日蛋糕 南极`,
		"戊": `胃 鼻 面 高冈 山冈 高原 军人 甜味 天门 中间 中央 守信用 诚实 诚信 五数 十数 坚强 稳定 稳固 可靠 呆板 城墙 黄色`,
		"己": `脾 脐轮 平原 田园 甜味 地户 中间 中央 六数 九数 十数 守信用 诚实 诚信 稳重 可靠 坟墓 地基 做事公正 平均 黄色`,
		"庚": `大肠 骨骼 辣味 金属制品 果断 刚强 矛戮 七数 八数 西方 刀具 兵器 仇人 敌人 讲义气 白色`,
		"辛": `肺 骨骼 手链 项链 耳环 刀具 辛辣 讲义气 果敢 切割 新生事物 肃杀 八数 七数 白色 尸骨 错误 手铐 针 铁钉 各种精小金属制品`,
		"壬": `膀胱 胫 大海 江 湖 河 聪明 智慧 流动 流行 咸味 九数 六数 黑色 血液循环 天牢 习惯 洪流 潮流 主流事物`,
		"癸": `肾 足 精 血 人体分泌物 阴私 暗昧 黑色 雨露 眼泪 聪明绝顶 极端 十数 五数 沼泽 水他 浴池 水塘 水库 北极`,
	}

	ganYinYangMap = map[string]int{
		"甲": 1, "丙": 1, "戊": 1, "庚": 1, "壬": 1,
		"乙": 0, "丁": 0, "己": 0, "辛": 0, "癸": 0}
	//十干寄宫
	shiGanJiGongMap = map[string]string{
		"甲": "寅",
		"乙": "辰",
		"丙": "巳",
		"戊": "巳",
		"丁": "未",
		"巳": "未",
		"庚": "申",
		"辛": "戌",
		"壬": "亥",
		"癸": "丑"}
	//十干禄
	shiGanLuMap = map[string]string{
		"甲": "寅",
		"乙": "卯",
		"丙": "巳",
		"丁": "午",
		"戊": "巳",
		"己": "午",
		"庚": "申",
		"辛": "酉",
		"壬": "亥",
		"癸": "子"}
	ganWuXingMap = map[string]string{
		"甲": "木", "乙": "木",
		"丙": "火", "丁": "火",
		"戊": "土", "己": "土",
		"庚": "金", "辛": "金",
		"壬": "水", "癸": "水",
	}
	wuXingShengMap = map[string]string{"木": "火", "火": "土", "土": "金", "金": "水", "水": "木"} //k生V
	wuXingKeMap    = map[string]string{"木": "土", "火": "金", "土": "水", "金": "木", "水": "火"} //k克v
	ganHuaHeMap    = map[string]string{
		"甲": "己", "己": "甲",
		"乙": "庚", "庚": "乙",
		"丙": "辛", "辛": "丙",
		"丁": "壬", "壬": "丁",
		"戊": "癸", "癸": "戊",
	} //k化合v
)

type TGan struct {
	YearGan  string `json:"year_gan"`
	MonthGan string `json:"month_gan"`
	DayGan   string `json:"day_gan"`
	HourGan  string `json:"hour_gan"`
}

func AliasYearGan() {

}
func AliasMonthGan() {

}
func AliasHourGan() {

}

// AliasGan 日干 1+mod(JD正午-1,10) 这里传入的JD是时间精确到日计算
func AliasGan(jd float64) string {
	n := int(math.Ceil(math.Mod(jd-1, 10)))
	gans := []string{"甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"}
	if n > 9 {
		n -= 10
	}
	return gans[n]
}

//Gan 天干
type Gan string

func NewGan(gan string) Gan {
	return Gan(gan)
}

// YiXiang 天干意象
func (g Gan) YiXiang() string {
	return shiGanYiXiangMap[string(g)]
}

// YinYang 阴阳属性 0阴 1阳
func (g Gan) YinYang() int {
	return ganYinYangMap[string(g)]
}

// Lu 禄
func (g Gan) Lu() string {
	return shiGanLuMap[string(g)]
}

// JiGong 寄宫
func (g Gan) JiGong() string {
	return shiGanJiGongMap[string(g)]
}

// ChangShengArray 十二长生数组 长生名称数组(0:长生 1:沐浴 2冠带 3临官 4帝旺 5衰 6病 7死 8墓 9绝 10胎 11:养)
func (g Gan) ChangShengArray() ([]string, []string) {
	return changShengMap[string(g)], changShengNames
}

//十干长生String
//如 传入天干甲 返回
func ChangShengString(gan string) string {
	xarr := changShengMap[gan]
	var s string
	for i := 0; i < len(xarr); i++ {
		s += changShengNames[i] + "于" + xarr[i] + " "
	}
	s = gan + s
	return s
}

// ChangSheng 干在支的十二长生名称
func (g Gan) ChangSheng(zhis string) string {
	return ChangSheng(string(g), zhis)
}

// ChangShengZhi 干在十二长生位置对应的地支
//传入天干 十二长生名称(长生 沐浴 冠带 临官 帝旺 衰 病 死 墓 绝 胎 养) 返回对应的地支
func (g Gan) ChangShengZhi(name string) string {
	return ChangShengZhi(string(g), name)
}

// ChangShengHide 十二长生
func (g Gan) ChangShengHide(name string) string {
	var s string
	switch name {
	case "长生":
		s = `万物之身，头、脑、骨髓、神经、心脏、肾，某事的开端、万事的基础，
物体的上上部位。风水的太极、坏境的中心点。阳宅的宅体
`
	case "沐浴":
		s = `万物之颈，口、咽、呼吸道、气管、动脉血管、肺，消化道、食道。某事的言商、万事的行动。
物体的上中部位。风水的来龙、环境的水路。男人的婚喜、女人的私情或谈婚，男女的生理系统。阳宅的水井
`
	case "冠戴":
		s = `万物之肩，乳房上、左锁骨、燕窝、斜方肌、胸锁乳突肌、三角肌、胸大肌。某事的操作、万事的起步。
物体的左右肩上、风水的左右龙虎煞、环境的内两侧。经济的来源、学业的发展。阳宅配房
`
	case "临官":
		s = `万物之肋，乳房下、服外斜肌。某事的关系、万事的进展。
物体的左右肩下、风水的左右龙虎煞、环境的外两侧。工作的职务、名誉的状况。阳宅配房
`
	case "帝旺":
		s = `万物中心、左微侧、胸口、左微侧肋骨、在脐之上、腱划。某事的顶峰、万事的成功。
物体的阳面。风水的明堂、环境的前面。经济的高峰、运气的高峰。阳宅的宅院
`
	case "衰":
		s = `万物中心、右微侧、胸口、右微侧肋骨、在脐之上、腱划。某事的低潮、万事的退败。
物体的阳面。风水的外明堂、环境的侧面。经济损财、物资的破坏、运气低估。阳宅的宅院
`
	case "病":
		s = `万物之体肢、四肢、胳膊、手、腿、足。某事的改革、万事的变化。
物体的不完整部位。风水为路口、环境为路线。经济破损、物资损坏、运气起伏不定。阳宅的出路
`
	case "死":
		s = `喷门、排泄道。某事争斗、万事辩证。人事官司、物资损伤。
风水去脉、环境沟凹。经济损失、运气不务实。阳宅的出水道
`
	case "墓":
		s = `胃、脾、膀胱、某事保守、万事晚成、人事疾病、物资尘封。
风水墓穴、环境坑凹、经济不佳、运气堵塞。阳宅的卧室
`
	case "绝":
		s = `肠道、十二指肠、结肠、某事失利、万事破败、人事受气、物资改装。
风水庙堂、环境凹陷、经济遗失、运气淡薄。阳宅的卫生间
`
	case "胎":
		s = `会阴、精血。某事小成、万事小利、人事意外、物资革新。
风水后山、环境微低、经济小失、运气初始。阳宅的厨房
`
	case "养":
		s = `肝、胆、睾丸。某事稳定、万事收益、人事喜悦、物资初成。
风水后山、环境平坦、经济丰食、运气平平。阳宅的餐厅
`
	}
	return s
}

// WuXing 五行
func (g Gan) WuXing() string {
	return ganWuXingMap[string(g)]
}

// WuXingShengKe 五行生克
func (g Gan) WuXingShengKe() (string, string) {
	wx := ganWuXingMap[string(g)]
	return WuXingShengKe(wx)
}

// WuXingShengKe 五行生克
func WuXingShengKe(wx string) (string, string) {
	var sheng, ke string
	if s, ok := wuXingShengMap[wx]; ok {
		sheng = s
	}
	if k, ok := wuXingKeMap[wx]; ok {
		ke = k
	}
	return sheng, ke
}

// HuaHe 化合 甲己合化土，乙庚合化金，丙辛合化水，丁壬合化木，戊癸合化火
func (g Gan) HuaHe(gan string) (bool, string) {
	huaHeMap := map[string]string{
		"甲": "土", "己": "土",
		"乙": "金", "庚": "金",
		"丙": "水", "辛": "水",
		"丁": "木", "壬": "木",
		"戊": "火", "癸": "火",
	}
	hegan := ganHuaHeMap[string(g)]
	if strings.EqualFold(gan, hegan) {
		return true, huaHeMap[string(g)]
	}
	return false, ""

}
