/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT.
 */

package gz

import (
	"fmt"
	"github.com/starainrt/astro/calendar"
	"testing"
	"time"
)

func TestWeekNumber(t *testing.T) {
	tx := time.Now().Local()
	for i := 0; i < 31; i++ {
		xt := time.Date(tx.Year(), tx.Month(), i, 0, 0, 0, 0, time.Local)
		jd := calendar.Date2JDE(xt)
		n := WeekNumber(jd)
		fmt.Println(xt.String()[:10], n)
	}
}
