/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT
 */
package gz

import "strings"

//返回xgz的地支合宫
func LiuHe(xgz string) string {
	hmap := map[string]string{
		"午": "未", "未": "午",
		"子": "丑", "丑": "子",
		"寅": "亥", "亥": "寅",
		"卯": "戌", "戌": "卯",
		"辰": "酉", "酉": "辰",
		"巳": "申", "申": "巳",
	}
	var s string
	for k, v := range hmap {
		if strings.Contains(xgz, k) {
			s = v
			break
		}
	}
	return s
}
