/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT
 */

package gz

import (
	"github.com/Aquarian-Age/xa/pkg/pub"
)

//阴阳贵人诀 返回干支对应的阳贵人　阴贵人
func GuiRenJue(dgz string) (yang, yin string) {
	gs := pub.GetGanS(dgz)
	switch gs {
	case "甲":
		yang = "未"
		yin = "丑"
	case "戊":
		yang = "丑"
		yin = "未"
	case "乙":
		yang = "申"
		yin = "子"
	case "己":
		yang = "子"
		yin = "申"
	case "丙":
		yang = "酉"
		yin = "亥"
	case "丁":
		yang = "亥"
		yin = "酉"
	case "庚":
		yang = "丑"
		yin = "未"
	case "辛":
		yang = "寅"
		yin = "午"
	case "壬":
		yang = "卯"
		yin = "巳"
	case "癸":
		yang = "巳"
		yin = "卯"
	}
	return
}
