/*
 * The code is automatically generated by the Goland.
 * Copyright © Aquarian-Age. All Rights Reserved.
 * Licensed under MIT
 */
package x

import (
	"fmt"
	"testing"
)

func TestLiuNianBiao(t *testing.T) {
	by := 1990
	s, s1 := LiuNianBiao(by)
	fmt.Println(s, "\n", s1)
}
